BEGIN TRANSACTION;

INSERT INTO living_situations (name) VALUES
	('Завести собаку'),
	('Стать волонтером'),
	('Беременность'),
	('Донорство'),
	('Завести домашнее животное'),
	('Развод'),
	('Прогулка с младенцем'),
	('Психические / психологические проблемы'),
	('Поездка на общественном транспорте'),
	('Профессиональное развитие'),
	('Насилие в семье'),
	('Травма'),
	('Спортивные развлечения с детьми'),
	('Улучшение условий жизни'),
	('Автомобильная авария'),
	('Поход в ТЦ'),
	('Травма ребенка'),
	('Посещение культурных объектов'),
	('Благотворительность'),
	('Посещение святыни'),
	('Развлечения с детьми'),
	('Развлечения'),
	('Посещение общественных пространств для молодежи'),
	('Изучение иностранного языка'),
	('Выезд за город'),
	('Употребление подростком наркотиков'),
	('Болезнь'),
	('Потеря работы'),
	('Улучшение успеваемости ребенка'),
	('Поход в ТЦ с младенцем'),
	('Мед. Осмотр ребенка'),
	('Посещение музеев и выставок'),
	('Прогулка на природе'),
	('Принять участие в субботнике'),
	('Мед. Осмотр'),
	('Занятия спортом для детей'),
	('Рождение ребенка'),
	('Смерть родственника'),
	('Пожар'),
	('Прогулка на природе с младенцем'),
	('Посещение воскресной школы'),
	('Покупка лекарств'),
	('Прогулка по городу'),
	('Прогулка на природе с ребенком'),
	('Посещение кафе с детьми'),
	('Паломничество'),
	('Попадание ребенка в тяжелую жизненную ситуацию'),
	('Покупка детских вещей'),
	('Отсутствие врача-педиатра'),
	('Усыновление ребенка'),
	('Посещение театров'),
	('Улучшение здоровья'),
	('Получение водительских прав'),
	('Обращение ребенка за психологической помощью'),
	('Болезнь ребенка'),
	('Спортивные развлечения'),
	('Обращение беременных за психологической помощью'),
	('Поход в ТЦ с ребенком'),
	('Поступление в ССУЗ'),
	('Поступление в вуз'),
	('Прогулка с детьми'),
	('Свадьба'),
	('Посещение научных конференций'),
	('Стать жертвой преступления'),
	('Посещение ресторана с детьми'),
	('Покупка продуктов и бытовых вещей'),
	('Обращение молодых родителей за психологической помощью'),
	('Посещение музеев и выставок с детьми'),
	('Развод с обременением'),
	('Посещение творческих кружков'),
	('Посещение кафе'),
	('Лечение зубов'),
	('Поездка на дачу'),
	('Ребенок ходит в школу'),
	('Посещение храмов и служб'),
	('Ребенок ходит в детский сад'),
	('Занятие у репетитора'),
	('Посещение ресторана'),
	('Посещение сомнительных мест'),
	('Занятие спортом'),
	('Поездка на личном транспорте');

INSERT INTO social_groups (name, code, social_group_value, parent_id) VALUES
	('До трудоспособного возраста', '1', null, (SELECT id FROM social_groups WHERE code = '')),
	('Младенцы (0)', '1.1', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Дети до-детсадовского возраста (1-2)', '1.2', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Дети дошкольного возраста (3-6)', '1.3', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Дети младшего школьного возраста (7-11)', '1.4', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Подростки младшего возраста (12-15)', '1.5', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Трудоспособные горожане', '2', null, (SELECT id FROM social_groups WHERE code = '')),
	('Подростки старшего возраста (16-18)', '2.1', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Молодые горожане (19-30)', '2.2', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Горожане среднего возраста (31-40)', '2.3', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Горожане старшего возраста (41-60)', '2.4', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Горожане старше трудоспособного возраста', '3', null, (SELECT id FROM social_groups WHERE code = '')),
	('Люди старшего возраста (61-75)', '3.1', 0.7, (SELECT id FROM social_groups WHERE code = '3')),
	('Люди преклонного возраста (старше 75)', '3.2', 0.7, (SELECT id FROM social_groups WHERE code = '3')),
	('Горожане с детьми', '4', null, (SELECT id FROM social_groups WHERE code = '')),
	('Беременные женщины', '4.1', 0.5, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с младенцами', '4.2', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми детсадовского возраста (1-3 года)', '4.3', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми дошкольного возраста (3-6 лет)', '4.4', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми младшего школьного возраста (7-11 лет)', '4.5', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с подростками (12-18 лет)', '4.6', 0.5, (SELECT id FROM social_groups WHERE code = '4')),
	('Специальные группы', '7', null, (SELECT id FROM social_groups WHERE code = '')),
	('Студенты и учащиеся колледжей', '7.1', 1.0, (SELECT id FROM social_groups WHERE code = '7'));

INSERT INTO city_infrastructure_types (name, code) VALUES
	('Базовая инфраструктура', 'basic'),
	('Социальная инфраструктура', 'social'),
	('Транспортная инфраструктура', 'transport'),
	('Инфраструктура обслуживания населения', 'public'),
	('Инфраструктура досуга', 'leisure'),
	('Туристическая инфраструктура', 'tourism');

INSERT INTO city_functions (name, code, city_infrastructure_type_id) VALUES
	('Жилье', 'residential', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Мусор', 'trash', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Образование', 'education', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Здравоохранение', 'health', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Религия', 'religion', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Социальное обслуживание', 'social', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Личный транспорт', 'car', (SELECT id FROM city_infrastructure_types WHERE code = 'transport')),
	('Уход за собой', 'care', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Продовольствие', 'rations', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Финансы', 'finance', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Товары', 'goods', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Питомцы', 'pet', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Культура, развлечения, творчество', 'culture', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Спорт', 'sport', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Питание', 'food', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Товары для туристов', 'tourist', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Жилье для приезжих', 'hotel', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Достопримечательности', 'sights', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Специализированные учреждения', 'special', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Дипломатическое представительство', 'diplomacy', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Пешеходное пространство', 'pedestrian', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Общественный транспорт', 'public_transport', (SELECT id FROM city_infrastructure_types WHERE code = 'transport')),
	('Доставка', 'delivery', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Услуги', 'service', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Природа', 'nature', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Военная структура', 'army', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Сервисы для маленьких детей', 'kids_services', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure'));

INSERT INTO city_service_types (name, code, city_function_id,       capacity_min, capacity_max, status_min, status_max, is_building, public_transport_time_normative, walking_radius_normative) VALUES
	('Детский сад', 'kindergartens', (SELECT id FROM city_functions WHERE code = 'education'), 1, 300, 9, 18, true, null, 300),
	('Школа', 'schools', (SELECT id FROM city_functions WHERE code = 'education'), 51, 1000, 12, 24, true, null, 500),
	('Учреждение среднего профессионального образования', 'colleges', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 18, 36, true, 30, null),
	('Учреждение высшего профессионального образования', 'universities', (SELECT id FROM city_functions WHERE code = 'education'), 601, 25000, 18, 36, true, 30, null),
	('Поликлиника', 'policlinics', (SELECT id FROM city_functions WHERE code = 'health'), 601, 6000, 12, 24, true, null, 1000),
	('Больница', 'hospitals', (SELECT id FROM city_functions WHERE code = 'health'), 151, 9000, 12, 24, true, 60, null),
	('Женская консультация', 'woman_doctors', (SELECT id FROM city_functions WHERE code = 'health'), 51, 600, 12, 24, true, null, 1000),
	('Роддом', 'maternity_hospitals', (SELECT id FROM city_functions WHERE code = 'health'), 1, 300, 18, 36, true, 60, null),
	('Стоматология', 'dentists', (SELECT id FROM city_functions WHERE code = 'health'), 1, 150, 6, 12, true, null, 1000),
	('Аптека', 'pharmacies', (SELECT id FROM city_functions WHERE code = 'health'), 1, 1000, 4, 8, true, null, 500),
	('Диспансер', 'health_centers', (SELECT id FROM city_functions WHERE code = 'health'), 51, 3000, 18, 36, true, null, 500),
	('Кладбище/крематорий', 'cemeteries', (SELECT id FROM city_functions WHERE code = 'religion'), 1, 300, 24, 36, false, 40, null),
	('Религиозный объект', 'churches', (SELECT id FROM city_functions WHERE code = 'religion'), 1, 3000, 12, 24, true, null, 2000),
	('Автозаправка', 'gas_stations', (SELECT id FROM city_functions WHERE code = 'car'), 151, 1000, 6, 12, false, null, 3000),
	('Электрозаправка', 'charging_stations', (SELECT id FROM city_functions WHERE code = 'car'), 1, 300, 6, 12, false, null, 100),
	('Рынок', 'markets', (SELECT id FROM city_functions WHERE code = 'rations'), 151, 3000, 9, 18, true, 20, null),
	('Магазин у дома', 'conveniences', (SELECT id FROM city_functions WHERE code = 'rations'), 151, 1000, 3, 6, true, null, 400),
	('Универсам/супермаркет/гипермаркет', 'supermarkets', (SELECT id FROM city_functions WHERE code = 'rations'), 601, 9000, 9, 18, true, null, 1500),
	('Арт пространство', 'art_spaces', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 600, 6, 12, true, 30, null),
	('Зоопарк', 'zoos', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 1000, 12, 24, true, 30, null),
	('Библиотека', 'libraries', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 300, 12, 24, true, 30, null),
	('Театр/Концертный зал', 'theaters', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 1000, 12, 24, true, 50, null),
	('Музей', 'museums', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 15000, 12, 24, true, 50, null),
	('Кинотеатр', 'cinemas', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 3000, 12, 24, true, 60, null),
	('Бар/Паб/Кальянная', 'bars', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true, null, 1000),
	('Булочная', 'bakeries', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true, null, 1000),
	('Кафе/столовая', 'cafes', (SELECT id FROM city_functions WHERE code = 'food'), 1, 1000, 3, 6, true, null, 1000),
	('Ресторан', 'restaurants', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true, 20, null),
	('Фастфуд', 'fastfoods', (SELECT id FROM city_functions WHERE code = 'food'), 1, 6000, 3, 6, true, null, 500),
	('Урна', 'garbage_containers', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 25000, 6, 12, false, null, 100),
	('Свалка', 'garbage_dumps', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 150, 12, 24, false, null, 1400),
	('Точка раздельного сбора', 'recycling_stations', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 600, 3, 6, false, null, 300),
	('Баня', 'saunas', (SELECT id FROM city_functions WHERE code = 'care'), 1, 300, 4, 8, true, 15, null),
	('Спортивная площадка', 'sportgrounds', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 300, 6, 12, false, null, 300),
	('Бассейн', 'swimming_pools', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 9, 18, true, 30, null),
	('Ветеринарная клиника', 'veterinaries', (SELECT id FROM city_functions WHERE code = 'pet'), 1, 300, 6, 12, true, 15, null),
	('Жилье', 'houses', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 15000, 8, 16, true, 30, null),
	('Отделение банка', 'banks', (SELECT id FROM city_functions WHERE code = 'finance'), 51, 300, 6, 12, true, 15, null),
	('Банкомат', 'atms', (SELECT id FROM city_functions WHERE code = 'finance'), 1, 300, 6, 12, true, null, 1300),
	('Полиция', 'police_stations', (SELECT id FROM city_functions WHERE code = 'special'), 1, 300, 12, 24, true, null, 2000),
	('Пожарная станция', 'fire_stations', (SELECT id FROM city_functions WHERE code = 'special'), 1, 300, 12, 24, true, 15, null),
	('Оптика', 'optics', (SELECT id FROM city_functions WHERE code = 'health'), 1, 1000, 4, 8, true, null, 500),
	('Торгово-развлекательный центр', 'shopping_centers', (SELECT id FROM city_functions WHERE code = 'culture'), 1001, 25000, 12, 24, true, 30, null),
	('Визовый центр', 'visa_centers', (SELECT id FROM city_functions WHERE code = 'diplomacy'), 1, 600, 6, 12, true, 40, null),
	('Консульство/посольство', 'consulates', (SELECT id FROM city_functions WHERE code = 'diplomacy'), 1, 1000, 12, 24, true, 30, null),
	('Клиника', 'clinics', (SELECT id FROM city_functions WHERE code = 'health'), 51, 1000, 6, 12, true, null, 500),
	('Аквапарк', 'aquaparks', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 12, 24, true, 60, null),
	('Фитнес клуб', 'fitness_clubs', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 6, 12, true, null, 1000),
	('Спортивный центр', 'sport_centers', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 12, 24, true, null, 500),
	('Спортивный клуб', 'sport_clubs', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 9, 18, true, null, 500),
	('Стадион', 'stadiums', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 18, 36, true, 40, null),
	('Гостиница', 'hotels', (SELECT id FROM city_functions WHERE code = 'hotel'), 51, 3000, 6, 12, true, 10, null),
	('Гостевой дом', 'guest_houses', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 300, 6, 12, true, 10, null),
	('Хостел', 'hostels', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 150, 6, 12, true, 15, null),
	('Общежитие', 'dormitories', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 150, 6, 12, true, 15, null),
	('Автосервис', 'repair_stations', (SELECT id FROM city_functions WHERE code = 'car'), 1, 150, 6, 12, true, 20, null),
	('Автопарковка', 'parkings', (SELECT id FROM city_functions WHERE code = 'car'), 1, 3000, 6, 12, false, null, 1000),
	('Салон красоты/парикмахерская', 'beauty_salons', (SELECT id FROM city_functions WHERE code = 'care'), 1, 150, 3, 6, true, 15, null),
	('Массажный салон (spa)', 'spas', (SELECT id FROM city_functions WHERE code = 'care'), 1, 150, 3, 6, true, 30, null),
	('Почта', 'post_offices', (SELECT id FROM city_functions WHERE code = 'delivery'), 151, 1000, 12, 24, true, null, 1000),
	('Пункт выдачи', 'outposts', (SELECT id FROM city_functions WHERE code = 'delivery'), 151, 3000, 6, 12, true, null, 15),
	('Почтовый ящик', 'post_boxes', (SELECT id FROM city_functions WHERE code = 'delivery'), 1, 1000, 12, 24, true, null, 400),
	('Жилищное (жкх, жилкомсервис)', 'housing_services', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 600, 12, 24, true, 30, null),
	('Детская площадка', 'playgrounds', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 15000, 6, 12, false, null, 500),
	('Станция скорой помощи', 'ambulance_stations', (SELECT id FROM city_functions WHERE code = 'health'), 51, 3000, 12, 24, true, null, 5000),
	('МФЦ', 'multifunctional_centers', (SELECT id FROM city_functions WHERE code = 'social'), 51, 3000, 12, 24, true, 20, null),
	('Суд', 'courts', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true, 30, null),
	('ИОГВ', 'executive_institutions', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true, 30, null),
	('ПФР', 'pension_funds', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true, 20, null),
	('Тюрьма', 'prisons', (SELECT id FROM city_functions WHERE code = 'special'), 151, 6000, 24, 48, true, 40, null),
	('Соц(Дом престарелых/Детский дом)', 'orphanages', (SELECT id FROM city_functions WHERE code = 'special'), 1, 1000, 18, 36, true, 30, null),
	('Государственное учреждение', 'state_institutions', (SELECT id FROM city_functions WHERE code = 'special'), 1, 1000, 18, 36, true, 20, null),
	('Станция метро', 'metro_stations', (SELECT id FROM city_functions WHERE code = 'public_transport'), 1, 150, 12, 24, false, 15, null),
	('Ремонт обуви и одежды', 'clothing_repairings', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true, 30, null),
	('Фотоателье', 'photo_studios', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true, null, 15),
	('Ремонт часов', 'watch_repairings', (SELECT id FROM city_functions WHERE code = 'service'), 1, 150, 4, 8, true, 30, null),
	('Букмекерская контора', 'bookmaker_offices', (SELECT id FROM city_functions WHERE code = 'service'), 51, 1000, 4, 8, true, 30, null),
	('Похоронные услуги', 'rituals', (SELECT id FROM city_functions WHERE code = 'service'), 1, 150, 9, 18, true, 30, null),
	('Хозяйственный', 'hardware_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 8, 16, true, null, 2000),
	('Инструменты', 'instrument_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 8, 16, true, 15, null),
	('Бытовая техника, электроника', 'electronic_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 600, 6, 12, true, 20, null),
	('Магазин одежды/обуви/аксессуаров', 'clothing_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 8, 16, true, 15, null),
	('Табак', 'tobacco_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 8, 16, true, null, 1000),
	('Спорттовары', 'sporting_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 6, 12, true, 20, null),
	('Ювелирная мастерская', 'jewelry_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 300, 6, 12, true, 30, null),
	('Цветы', 'flower_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 300, 6, 12, true, null, 1500),
	('Ломбард', 'pawnshops', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 6, 12, true, null, 2000),
	('Зоомагазин', 'pet_shops', (SELECT id FROM city_functions WHERE code = 'pet'), 1, 600, 4, 8, true, null, 800),
	('Площадка для выгула собак', 'dog_playgrounds', (SELECT id FROM city_functions WHERE code = 'pet'), 51, 1000, 6, 12, false, 20, null),
	('Рекреационная зона', 'recreational_areas', (SELECT id FROM city_functions WHERE code = 'nature'), 1, 6000, 12, 24, false, null, 200),
	('Набережная', 'embankments', (SELECT id FROM city_functions WHERE code = 'nature'), 51, 1000, 24, 36, false, 10, null),
	('Магазин сувениров', 'souvenir_shops', (SELECT id FROM city_functions WHERE code = 'tourist'), 1, 3000, 9, 18, true, 15, null),
	('Достопримечательность', 'sights', (SELECT id FROM city_functions WHERE code = 'sights'), 1, 25000, 12, 24, false, 30, null),
	('Боулинг, бильярд', 'bowlings', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 1000, 6, 12, true, 30, null),
	('Органы опеки', 'child_protections', (SELECT id FROM city_functions WHERE code = 'special'), 51, 600, 18, 36, true, 15, null),
	('Мусоро-перерабатывающий завод', 'wasterecycling_plants', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 150, 12, 24, true, 30, null),
	('Улица', 'streets', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false, 30, null),
	('Пешеходный переход', 'crosswalks', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false, null, 10),
	('Пешеходная дорожка', 'footpaths', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false, null, 5),
	('Хоспис', 'hospices', (SELECT id FROM city_functions WHERE code = 'health'), 1, 600, 18, 36, true, 40, null),
	('Центр социальной помощи', 'social_assistance_centers', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true, 20, null),
	('Паспортный стол', 'passport_offices', (SELECT id FROM city_functions WHERE code = 'social'), 51, 1000, 12, 24, true, 20, null),
	('Миграционная служба', 'migration_services', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true, 40, null),
	('Прокуратура', 'prosecutor_offices', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true, 30, null),
	('Судебные приставы', 'bailiffs', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true, 30, null),
	('Остановка общественного транспорта', 'stops', (SELECT id FROM city_functions WHERE code = 'public_transport'), 601, 25000, 12, 24, false, null, 10),
	('Клуб', 'clubs', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 3000, 6, 12, true, 40, null),
	('Услуги', 'services', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true, 30, null),
	('Травмпункт', 'injury_service', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, null, 20),
	('Кабинет врача-психолога', 'psychology', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 30, null),
	('Нотариальная контора', 'notary', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 20, null),
	('Психиатрическая больница', 'mental_hospital', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 30, null),
	('Военная часть', 'military_unit', (SELECT id FROM city_functions WHERE code = 'army'), 151, 3000, 6, 12, false, 30, null),
	('Кадровое агентство', 'recruitment_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Страховая служба', 'insurance', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Служба оценки имущества', 'property_appraisal', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Юридические услуги', 'legal_services', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 20, null),
	('Лабораторная служба', 'laboratory_service', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Пункт вакцинации', 'vaccination', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, null, 20),
	('Морг', 'morgue', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 40, null),
	('Диагностический центр', 'diagnostic_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Аварийная служба', 'traffic_service', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true, 30, null),
	('Эвакуатор', 'tow_truck', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true, 30, null),
	('ГИБДД', 'traffic_police', (SELECT id FROM city_functions WHERE code = 'special'), 151, 3000, 6, 12, true, 30, null),
	('Психоневрологический диспансер', 'psychoneurological_dispensary', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 30, null),
	('Кризисный центр', 'crisis_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 30, null),
	('Реабилитационный центр', 'rehabilitation_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Центр занятости населения', 'employment_center', (SELECT id FROM city_functions WHERE code = 'social'), 151, 3000, 6, 12, true, 30, null),
	('Микрозайм', 'microloan', (SELECT id FROM city_functions WHERE code = 'finance'), 151, 3000, 6, 12, true, 30, null),
	('Благотворительный фонд', 'charitable_foundations', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Налоговая служба', 'tax_office', (SELECT id FROM city_functions WHERE code = 'special'), 151, 3000, 6, 12, true, 30, null),
	('ЗАГС', 'registry_office', (SELECT id FROM city_functions WHERE code = 'social'), 151, 3000, 6, 12, true, 30, null),
	('Детская поликлиника', 'child_doctor', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Детская больница', 'child_hospital', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Детский реабилитационный центр/санаторий', 'child_rehabilitation_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 40, null),
	('Детский хоспис', 'child_hospice', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 40, null),
	('Клуб для детей и подростков', 'child_teenager_club', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 20, null),
	('Спортивная секция', 'sport_section', (SELECT id FROM city_functions WHERE code = 'sport'), 151, 3000, 6, 12, false, null, 20),
	('Частный детский сад', 'private_kids_garden', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, null, 15),
	('Центр подготовки к ОГЭ/ЕГЭ', 'center_ege', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, 15, null),
	('Железнодорожный вокзал', 'railway_terminal', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false, 30, null),
	('Автобусный вокзал', 'bus_terminal', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false, 40, null),
	('Железнодорожная станция', 'railway_station', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false, 30, null),
	('Дом творчества/культуры', 'culture_house', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 20, null),
	('Квест', 'quest', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 40, null),
	('Цирк', 'circus', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 30, null),
	('Центр развития ребенка', 'child_development_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, null, 20),
	('Детский диспансер', 'children_dispensary', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Детская стоматология', 'child_dental', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 20, null),
	('Детская игровая комната', 'child_game_room', (SELECT id FROM city_functions WHERE code = 'kids_services'), 151, 3000, 6, 12, true, 30, null),
	('Детские товары + для беременных', 'child_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true, 30, null),
	('Картинная галерея', 'art_gallery', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 40, null),
	('Книжный магазин', 'book_store', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true, 20, null),
	('Музыкальная школа', 'music_school', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true, 20, null),
	('Магазин товаров для творчества и рукоделия', 'art_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true, 30, null),
	('Комната матери и ребенка', 'mother_child_room', (SELECT id FROM city_functions WHERE code = 'kids_services'), 151, 3000, 6, 12, true, 30, null),
	('Прокат велосипедов', 'bike_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false, 30, null),
	('Прокат автомобилей', 'car_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false, 30, null),
	('Прокат самокатов', 'scooter_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false, 30, null),
	('Товары для праздника', 'holiday_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true, 30, null),
	('Курсы иностранного языка (языковая школа)', 'language_school', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, 30, null),
	('Магазин игрушек', 'toy_store', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true, 30, null),
	('Копировальный центр', 'copy_center', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Приют для животных', 'animal_shelter', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true, 30, null),
	('Питомник', 'nursery', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true, 30, null),
	('Птичий рынок', 'pet_market', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true, 30, null),
	('Агентство недвижимости', 'real_estate_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Свадебное агентство', 'wedding_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Прокат лимузинов', 'limousine_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false, 30, null),
	('Туристическое агентство', 'tourist_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true, 30, null),
	('Автосалон', 'car_showroom', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true, 40, null),
	('Автошкола', 'driving_schools', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true, 30, null),
	('Санаторий', 'sanatorium', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true, 30, null),
	('Центр дополнительного образования', 'continuing_education_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, 20, null),
	('Центр повышения квалификации', 'advanced_training_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, 20, null),
	('Частная школа', 'private_school', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true, null, 15),
	('Военный комиссариат', 'military_commissariat', (SELECT id FROM city_functions WHERE code = 'army'), 151, 3000, 6, 12, true, 30, null),
	('Общежитие для студентов', 'dormetory', (SELECT id FROM city_functions WHERE code = 'residential'), 151, 3000, 6, 12, true, 30, null),
	('Пляж', 'beach', (SELECT id FROM city_functions WHERE code = 'nature'), 151, 3000, 6, 12, false, 30, null),
	('Парк развлечений', 'amusement_park', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, false, 40, null),
	('Объект культурного наследия', 'culture_object', (SELECT id FROM city_functions WHERE code = 'sights'), 1500, 25000, 12, 24, false, 20, null);

INSERT INTO municipality_types (full_name, short_name) VALUES
	('поселок', 'п.'),
	('муниципальный округ', 'м.о.'),
	('город', 'г.'),
	('городской округ', 'г.о.'),
	('сельское поселение', 'с.п.'),
	('городское поселение', 'г.п.');

INSERT INTO administrative_unit_types (full_name, short_name) VALUES
	('район', 'р-н'),
	('внутригородской округ', 'вн.о.'),
	('сельский округ', 'с.о.');

END TRANSACTION;
