BEGIN TRANSACTION;

INSERT INTO living_situations (name) VALUES
	('Типичный нерабочий день'),
	('Типичный рабочий день'),
	('Природный катаклизм (Изменение климата / аномальная погода / аномальные температуры)'),
	('Эпидемия'),
	('Пожар в квартире / доме'),
	('Авария'),
	('Обрушение дома / снос дома по причине износа'),
	('Техногенная авария'),
	('Отключение электричества / воды и тд'),
	('Исключение из школы'),
	('Зависимость от вредных привычек / наркотиков / алкоголя'),
	('Не сдать выпускные экзамены'),
	('Проблемы в семье / Насилие внутри семьи'),
	('Смерть родителя / родителей'),
	('Стать жертвой преступления'),
	('Ребенок сбежал из дома'),
	('Стать жертвой мошенников'),
	('Травля сверстников'),
	('Порча чужого имущества'),
	('Психические / психологические проблемы'),
	('Аборт'),
	('Болезнь'),
	('Болезнь / травма / смерть ребенка'),
	('Болезнь / травма / смерть родителей'),
	('Употребление подростком наркотиков'),
	('Угроза жизни ребенку / выкидыш'),
	('Травма'),
	('Потеря работы'),
	('Лишение жилья'),
	('Лишение родительских прав'),
	('Отмена льгот'),
	('Отмена материнского капитала'),
	('Развод'),
	('Нет места в детском саду'),
	('Нет места в яслях'),
	('Нет места в школе'),
	('Рост цен на товары и услуги первой необходимости, лекарства'),
	('Отсутствие врача-педиатра'),
	('Закрытие ближайшего магазина к дому'),
	('Отсутствие развивающих кружков для детей'),
	('Игра на детской площадке'),
	('Посещение социальных объектов'),
	('Прогулка по городу'),
	('Посещение школы'),
	('Посещение образовательных учреждений (школа, колледж, институт)'),
	('Занятие у репетитора'),
	('Посещение работы'),
	('Посещение развлекательных мероприятий (парк аттракционов, зоопарки, кинотеатры) с детьми'),
	('Посещение инфраструктуры культура, развлечения, творчества'),
	('Использование шерниговых сервисов (самокаты, велосипеды)'),
	('Сопровождение детей до секций / кружков'),
	('Покупка продуктов питания'),
	('Посещение детских медицинских учреждений'),
	('Использование общественного / личного транспорта'),
	('Посещение медицинских учреждений'),
	('Поход в магазины и ТЦ'),
	('Посещение инфраструктуры питания'),
	('Сопровождение ребенка до школы'),
	('Посещений спортивных секций, кружков, мероприятий'),
	('Посещение культурных объектов (театры, музеи, выставки) с детьми'),
	('Поездка на дачу / сад'),
	('Прогулка на природе'),
	('Поездка за город'),
	('Проведение своего мероприятия'),
	('Участие в творческом конкурсе'),
	('Приобретение загородного дома'),
	('Участие в соревновании'),
	('Окончание младшей школы'),
	('Увеличение дохода'),
	('Появление еще одного ребенка'),
	('Успешное окончание ребенком школы'),
	('Вступление в брак'),
	('Поиск отдельного жилья'),
	('Приобретение жилья'),
	('Создание творческого кружка'),
	('Улучшение условий жизни'),
	('Стать родителем'),
	('Участие в общественно-политической жизни города'),
	('Рождение ребенка'),
	('Повышение'),
	('Поступление в институт / колледж'),
	('Поступление в программу образования выше (магистратура, ВУЗ)'),
	('Наличие университета для ребенка'),
	('Изучение иностранного языка'),
	('Получение работы'),
	('Сохранение работы'),
	('Окончание университета'),
	('Окончание средней школы'),
	('Возвращение на работу'),
	('Сдача ГИА'),
	('Первая работа / Подработка'),
	('Получение водительских прав'),
	('Открыть бизнес'),
	('Наличие объектов досуга / культуры для ребенка'),
	('Нахождение группы (секции) для развития ребенка'),
	('Культурное развитие'),
	('Наличие хорошей детской поликлиники'),
	('Сохранение здоровья ребенка'),
	('Возможность отдыха на свежем воздухе'),
	('Оздоровительные процедуры для ребенка'),
	('Сохранение здоровья'),
	('Занятия физическими упражнениями'),
	('Улучшить здоровье'),
	('Поддержание здоровья'),
	('Запись ребенка в детский сад'),
	('Улучшение успеваемости ребенка'),
	('Наличие детской площадки'),
	('Посещение праздника друга'),
	('Завести домашнее животное'),
	('Запись ребенка в школу'),
	('Стать жертвой мошенника / насильника / маньяка'),
	('Потеря работы / стипендии'),
	('Порча имущества'),
	('Ухудшение здоровья'),
	('Повышение цен'),
	('Потеря места жительства'),
	('Отсутствие в шаговой доступности развивающих кружков для детей'),
	('Отчисление из учебного заведения'),
	('Использование общественного транспорта'),
	('Посещение медицинских учереждений'),
	('Посещение медецинских учереждений'),
	('Поездка на общественном транспорте'),
	('Поездка на работу'),
	('Посещение детских медицинских учереждений'),
	('Поход в детский сад'),
	('Посещение культурных объектов (театры, музеи, выставки)'),
	('Посещение развлекательных мероприятий (парк аттракционов, зоопарки, кинотеатры)'),
	('Участие в спортивных соревнованиях'),
	('Окончание учебного заведения');

INSERT INTO social_groups (name, code, social_group_value, parent_id) VALUES
	('До трудоспособного возраста', '1', null, (SELECT id FROM social_groups WHERE code = '')),
	('Трудоспособные горожане', '2', null, (SELECT id FROM social_groups WHERE code = '')),
	('Горожане старше трудоспособного возраста', '3', null, (SELECT id FROM social_groups WHERE code = '')),
	('Горожане с детьми', '4', null, (SELECT id FROM social_groups WHERE code = '')),
	('Инвалиды', '5', null, (SELECT id FROM social_groups WHERE code = '')),
	('Туристы', '6', null, (SELECT id FROM social_groups WHERE code = '')),
	('Специальные группы', '7', null, (SELECT id FROM social_groups WHERE code = '')),
	('Студенты и учащиеся колледжей', '7.1', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Владельцы собак', '7.2', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Мотоциклисты', '7.4', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Велосипедисты', '7.5', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Верующие, православные', '7.7', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Верующие, мусульмане', '7.8', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Верующие, иудеи', '7.9', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Горожане, ведущие раздельный сбор мусора', '7.10', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Горожане, занимающиеся спортом', '7.11', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Горожане, ведущие активный образ жизни', '7.12', 1.0, (SELECT id FROM social_groups WHERE code = '7')),
	('Автовладельцы', '7.3', 0.8, (SELECT id FROM social_groups WHERE code = '7')),
	('Трудовые мигранты', '7.6', 0.6, (SELECT id FROM social_groups WHERE code = '7')),
	('Самозанятые горожане', '7.13', 0.8, (SELECT id FROM social_groups WHERE code = '7')),
	('Дети младшего школьного возраста (7-11)', '1.4', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Подростки младшего возраста (12-15)', '1.5', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Младенцы (0)', '1.1', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Дети до-детсадовского возраста (1-2)', '1.2', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Дети до-дошкольного возраста (3-6)', '1.3', 1.0, (SELECT id FROM social_groups WHERE code = '1')),
	('Подростки старшего возраста (16-18)', '2.1', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Молодые работающие горожане (до 30 лет)', '2.2', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Работающие горожане среднего возраста (30-40)', '2.3', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Работающие горожане старшего возраста (40-60)', '2.4', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Работающие горожане пенсионного возраста (60+)', '2.5', 1.0, (SELECT id FROM social_groups WHERE code = '2')),
	('Люди старшего возраста (60-75 лет)', '3.1', 0.7, (SELECT id FROM social_groups WHERE code = '3')),
	('Люди преклонного возраста (старше 75 лет)', '3.2', 0.7, (SELECT id FROM social_groups WHERE code = '3')),
	('Беременные женщины', '4.1', 0.5, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с младенцами', '4.2', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми до-детсадовского возраста (1-3)', '4.3', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми дошкольного возраста (3-7)', '4.4', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с детьми младшего школьного возраста (7-11)', '4.5', 0.6, (SELECT id FROM social_groups WHERE code = '4')),
	('Горожане с подростками (12-18)', '4.6', 0.5, (SELECT id FROM social_groups WHERE code = '4')),
	('Лица с инвалидностью по зрению', '5.1', 0.1, (SELECT id FROM social_groups WHERE code = '5')),
	('Лица с ограниченными возможностями передвижения', '5.2', 0.1, (SELECT id FROM social_groups WHERE code = '5')),
	('Туристы в составе организованных групп', '6.1', 0.5, (SELECT id FROM social_groups WHERE code = '6')),
	('Неорганизованные туристы', '6.2', 1.0, (SELECT id FROM social_groups WHERE code = '6')),
	('Приезжие к мероприятиям', '6.3', 1.0, (SELECT id FROM social_groups WHERE code = '6')),
	('Приезжие по рабочим вопросам', '6.4', 1.0, (SELECT id FROM social_groups WHERE code = '6'));

INSERT INTO city_infrastructure_types (name, code) VALUES
	('Базовая инфраструктура', 'basic'),
	('Социальная инфраструктура', 'social'),
	('Транспортная инфраструктура', 'transport'),
	('Инфраструктура обслуживания населения', 'public'),
	('Инфраструктура досуга', 'leisure'),
	('Туристическая инфраструктура', 'tourism');

INSERT INTO city_functions (name, code, city_infrastructure_type_id) VALUES
	('Жилье', 'residential', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Мусор', 'trash', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Образование', 'education', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Здравоохранение', 'health', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Религия', 'religion', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Социальное обслуживание', 'social', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Личный транспорт', 'car', (SELECT id FROM city_infrastructure_types WHERE code = 'transport')),
	('Уход за собой', 'care', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Продовольствие', 'rations', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Финансы', 'finance', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Товары', 'goods', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Питомцы', 'pet', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Культура, развлечения, творчество', 'culture', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Спорт', 'sport', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Питание', 'food', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Товары для туристов', 'tourist', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Жилье для приезжих', 'hotel', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Достопримечательности', 'sights', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Специализированные учреждения', 'special', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Дипломатическое представительство', 'diplomacy', (SELECT id FROM city_infrastructure_types WHERE code = 'tourism')),
	('Пешеходное пространство', 'pedestrian', (SELECT id FROM city_infrastructure_types WHERE code = 'basic')),
	('Общественный транспорт', 'public_transport', (SELECT id FROM city_infrastructure_types WHERE code = 'transport')),
	('Доставка', 'delivery', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Услуги', 'service', (SELECT id FROM city_infrastructure_types WHERE code = 'public')),
	('Природа', 'nature', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure')),
	('Военная структура', 'army', (SELECT id FROM city_infrastructure_types WHERE code = 'social')),
	('Сервисы для маленьких детей', 'kids_services', (SELECT id FROM city_infrastructure_types WHERE code = 'leisure'));

INSERT INTO city_service_types (name, code, city_function_id, capacity_min, capacity_max, status_min, status_max, is_building) VALUES
	('Детский сад', 'kindergartens', (SELECT id FROM city_functions WHERE code = 'education'), 1, 300, 9, 18, true),
	('Школа', 'schools', (SELECT id FROM city_functions WHERE code = 'education'), 51, 1000, 12, 24, true),
	('Учреждение среднего профессионального образования', 'colleges', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 18, 36, true),
	('Учреждение высшего профессионального образования', 'universities', (SELECT id FROM city_functions WHERE code = 'education'), 601, 25000, 18, 36, true),
	('Поликлиника', 'policlinics', (SELECT id FROM city_functions WHERE code = 'health'), 601, 6000, 12, 24, true),
	('Больница', 'hospitals', (SELECT id FROM city_functions WHERE code = 'health'), 151, 9000, 12, 24, true),
	('Женская консультация', 'woman_doctors', (SELECT id FROM city_functions WHERE code = 'health'), 51, 600, 12, 24, true),
	('Роддом', 'maternity_hospitals', (SELECT id FROM city_functions WHERE code = 'health'), 1, 300, 18, 36, true),
	('Стоматология', 'dentists', (SELECT id FROM city_functions WHERE code = 'health'), 1, 150, 6, 12, true),
	('Аптека', 'pharmacies', (SELECT id FROM city_functions WHERE code = 'health'), 1, 1000, 4, 8, true),
	('Диспансер', 'health_centers', (SELECT id FROM city_functions WHERE code = 'health'), 51, 3000, 18, 36, true),
	('Кладбище/крематорий', 'cemeteries', (SELECT id FROM city_functions WHERE code = 'religion'), 1, 300, 24, 36, false),
	('Религиозный объект', 'churches', (SELECT id FROM city_functions WHERE code = 'religion'), 1, 3000, 12, 24, true),
	('Автозаправка', 'gas_stations', (SELECT id FROM city_functions WHERE code = 'car'), 151, 1000, 6, 12, false),
	('Электрозаправка', 'charging_stations', (SELECT id FROM city_functions WHERE code = 'car'), 1, 300, 6, 12, false),
	('Рынок', 'markets', (SELECT id FROM city_functions WHERE code = 'rations'), 151, 3000, 9, 18, true),
	('Магазин у дома', 'conveniences', (SELECT id FROM city_functions WHERE code = 'rations'), 151, 1000, 3, 6, true),
	('Универсам/супермаркет/гипермаркет', 'supermarkets', (SELECT id FROM city_functions WHERE code = 'rations'), 601, 9000, 9, 18, true),
	('Арт пространство', 'art_spaces', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 600, 6, 12, true),
	('Зоопарк', 'zoos', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 1000, 12, 24, true),
	('Библиотека', 'libraries', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 300, 12, 24, true),
	('Театр/Концертный зал', 'theaters', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 1000, 12, 24, true),
	('Музей', 'museums', (SELECT id FROM city_functions WHERE code = 'culture'), 51, 15000, 12, 24, true),
	('Кинотеатр', 'cinemas', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 3000, 12, 24, true),
	('Бар/Паб/Кальянная', 'bars', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true),
	('Булочная', 'bakeries', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true),
	('Кафе/столовая', 'cafes', (SELECT id FROM city_functions WHERE code = 'food'), 1, 1000, 3, 6, true),
	('Ресторан', 'restaurants', (SELECT id FROM city_functions WHERE code = 'food'), 1, 600, 3, 6, true),
	('Фастфуд', 'fastfoods', (SELECT id FROM city_functions WHERE code = 'food'), 1, 6000, 3, 6, true),
	('Урна', 'garbage_containers', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 25000, 6, 12, false),
	('Свалка', 'garbage_dumps', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 150, 12, 24, false),
	('Точка раздельного сбора', 'recycling_stations', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 600, 3, 6, false),
	('Баня', 'saunas', (SELECT id FROM city_functions WHERE code = 'care'), 1, 300, 4, 8, true),
	('Спортивная площадка', 'sportgrounds', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 300, 6, 12, false),
	('Бассейн', 'swimming_pools', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 9, 18, true),
	('Ветеринарная клиника', 'veterinaries', (SELECT id FROM city_functions WHERE code = 'pet'), 1, 300, 6, 12, true),
	('Жилье', 'houses', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 15000, 8, 16, true),
	('Отделение банка', 'banks', (SELECT id FROM city_functions WHERE code = 'finance'), 51, 300, 6, 12, true),
	('Банкомат', 'atms', (SELECT id FROM city_functions WHERE code = 'finance'), 1, 300, 6, 12, true),
	('Полиция', 'police_stations', (SELECT id FROM city_functions WHERE code = 'special'), 1, 300, 12, 24, true),
	('Пожарная станция', 'fire_stations', (SELECT id FROM city_functions WHERE code = 'special'), 1, 300, 12, 24, true),
	('Оптика', 'optics', (SELECT id FROM city_functions WHERE code = 'health'), 1, 1000, 4, 8, true),
	('Торгово-развлекательный центр', 'shopping_centers', (SELECT id FROM city_functions WHERE code = 'culture'), 1001, 25000, 12, 24, true),
	('Визовый центр', 'visa_centers', (SELECT id FROM city_functions WHERE code = 'diplomacy'), 1, 600, 6, 12, true),
	('Консульство/посольство', 'consulates', (SELECT id FROM city_functions WHERE code = 'diplomacy'), 1, 1000, 12, 24, true),
	('Клиника', 'clinics', (SELECT id FROM city_functions WHERE code = 'health'), 51, 1000, 6, 12, true),
	('Аквапарк', 'aquaparks', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 12, 24, true),
	('Фитнес клуб', 'fitness_clubs', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 6, 12, true),
	('Спортивный центр', 'sport_centers', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 12, 24, true),
	('Спортивный клуб', 'sport_clubs', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 9, 18, true),
	('Стадион', 'stadiums', (SELECT id FROM city_functions WHERE code = 'sport'), 1, 600, 18, 36, true),
	('Гостиница', 'hotels', (SELECT id FROM city_functions WHERE code = 'hotel'), 51, 3000, 6, 12, true),
	('Гостевой дом', 'guest_houses', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 300, 6, 12, true),
	('Хостел', 'hostels', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 150, 6, 12, true),
	('Общежитие', 'dormitories', (SELECT id FROM city_functions WHERE code = 'hotel'), 1, 150, 6, 12, true),
	('Автосервис', 'repair_stations', (SELECT id FROM city_functions WHERE code = 'car'), 1, 150, 6, 12, true),
	('Автопарковка', 'parkings', (SELECT id FROM city_functions WHERE code = 'car'), 1, 3000, 6, 12, false),
	('Салон красоты/парикмахерская', 'beauty_salons', (SELECT id FROM city_functions WHERE code = 'care'), 1, 150, 3, 6, true),
	('Массажный салон (spa)', 'spas', (SELECT id FROM city_functions WHERE code = 'care'), 1, 150, 3, 6, true),
	('Почта', 'post_offices', (SELECT id FROM city_functions WHERE code = 'delivery'), 151, 1000, 12, 24, true),
	('Пункт выдачи', 'outposts', (SELECT id FROM city_functions WHERE code = 'delivery'), 151, 3000, 6, 12, true),
	('Почтовый ящик', 'post_boxes', (SELECT id FROM city_functions WHERE code = 'delivery'), 1, 1000, 12, 24, true),
	('Жилищное (жкх, жилкомсервис)', 'housing_services', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 600, 12, 24, true),
	('Детская площадка', 'playgrounds', (SELECT id FROM city_functions WHERE code = 'residential'), 1, 15000, 6, 12, false),
	('Станция скорой помощи', 'ambulance_stations', (SELECT id FROM city_functions WHERE code = 'health'), 51, 3000, 12, 24, true),
	('МФЦ', 'multifunctional_centers', (SELECT id FROM city_functions WHERE code = 'social'), 51, 3000, 12, 24, true),
	('Суд', 'courts', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true),
	('ИОГВ', 'executive_institutions', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true),
	('ПФР', 'pension_funds', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true),
	('Тюрьма', 'prisons', (SELECT id FROM city_functions WHERE code = 'special'), 151, 6000, 24, 48, true),
	('Соц(Дом престарелых/Детский дом)', 'orphanages', (SELECT id FROM city_functions WHERE code = 'special'), 1, 1000, 18, 36, true),
	('Государственное учреждение', 'state_institutions', (SELECT id FROM city_functions WHERE code = 'special'), 1, 1000, 18, 36, true),
	('Станция метро', 'metro_stations', (SELECT id FROM city_functions WHERE code = 'public_transport'), 1, 150, 12, 24, false),
	('Ремонт обуви и одежды', 'clothing_repairings', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true),
	('Фотоателье', 'photo_studios', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true),
	('Ремонт часов', 'watch_repairings', (SELECT id FROM city_functions WHERE code = 'service'), 1, 150, 4, 8, true),
	('Букмекерская контора', 'bookmaker_offices', (SELECT id FROM city_functions WHERE code = 'service'), 51, 1000, 4, 8, true),
	('Похоронные услуги', 'rituals', (SELECT id FROM city_functions WHERE code = 'service'), 1, 150, 9, 18, true),
	('Хозяйственный', 'hardware_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 8, 16, true),
	('Инструменты', 'instrument_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 8, 16, true),
	('Бытовая техника, электроника', 'electronic_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 600, 6, 12, true),
	('Магазин одежды/обуви/аксессуаров', 'clothing_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 8, 16, true),
	('Табак', 'tobacco_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 8, 16, true),
	('Спорттовары', 'sporting_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 25000, 6, 12, true),
	('Ювелирная мастерская', 'jewelry_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 300, 6, 12, true),
	('Цветы', 'flower_stores', (SELECT id FROM city_functions WHERE code = 'goods'), 51, 300, 6, 12, true),
	('Ломбард', 'pawnshops', (SELECT id FROM city_functions WHERE code = 'goods'), 1, 150, 6, 12, true),
	('Зоомагазин', 'pet_shops', (SELECT id FROM city_functions WHERE code = 'pet'), 1, 600, 4, 8, true),
	('Площадка для выгула собак', 'dog_playgrounds', (SELECT id FROM city_functions WHERE code = 'pet'), 51, 1000, 6, 12, false),
	('Рекреационная зона', 'recreational_areas', (SELECT id FROM city_functions WHERE code = 'nature'), 1, 6000, 12, 24, false),
	('Набережная', 'embankments', (SELECT id FROM city_functions WHERE code = 'nature'), 51, 1000, 24, 36, false),
	('Магазин сувениров', 'souvenir_shops', (SELECT id FROM city_functions WHERE code = 'tourist'), 1, 3000, 9, 18, true),
	('Достопримечательность', 'sights', (SELECT id FROM city_functions WHERE code = 'sights'), 1, 25000, 12, 24, false),
	('Боулинг, бильярд', 'bowlings', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 1000, 6, 12, true),
	('Органы опеки', 'child_protections', (SELECT id FROM city_functions WHERE code = 'special'), 51, 600, 18, 36, true),
	('Мусоро-перерабатывающий завод', 'wasterecycling_plants', (SELECT id FROM city_functions WHERE code = 'trash'), 1, 150, 12, 24, true),
	('Улица', 'streets', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false),
	('Пешеходный переход', 'crosswalks', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false),
	('Пешеходная дорожка', 'footpaths', (SELECT id FROM city_functions WHERE code = 'pedestrian'), 1, 25000, 12, 24, false),
	('Хоспис', 'hospices', (SELECT id FROM city_functions WHERE code = 'health'), 1, 600, 18, 36, true),
	('Центр социальной помощи', 'social_assistance_centers', (SELECT id FROM city_functions WHERE code = 'social'), 51, 300, 12, 24, true),
	('Паспортный стол', 'passport_offices', (SELECT id FROM city_functions WHERE code = 'social'), 51, 1000, 12, 24, true),
	('Миграционная служба', 'migration_services', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true),
	('Прокуратура', 'prosecutor_offices', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true),
	('Судебные приставы', 'bailiffs', (SELECT id FROM city_functions WHERE code = 'special'), 1, 600, 18, 36, true),
	('Остановка общественного транспорта', 'stops', (SELECT id FROM city_functions WHERE code = 'public_transport'), 601, 25000, 12, 24, false),
	('Клуб', 'clubs', (SELECT id FROM city_functions WHERE code = 'culture'), 1, 3000, 6, 12, true),
	('Услуги', 'services', (SELECT id FROM city_functions WHERE code = 'service'), 1, 300, 4, 8, true),
	('Травмпункт', 'injury_service', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Кабинет врача-психолога', 'psychology', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Нотариальная контора', 'notary', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Психиатрическая больница', 'mental_hospital', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Военная часть', 'military_unit', (SELECT id FROM city_functions WHERE code = 'army'), 151, 3000, 6, 12, false),
	('Кадровое агентство', 'recruitment_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Страховая служба', 'insurance ', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Служба оценки имущества', 'property_appraisal ', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Юридические услуги', 'legal_services', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Лабораторная служба', 'laboratory_service', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Пункт вакцинации', 'vaccination', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Морг', 'morgue', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Диагностический центр', 'diagnostic_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Аварийная служба', 'traffic_service', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true),
	('Эвакуатор', 'tow_truck', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true),
	('ГИБДД', 'traffic_police', (SELECT id FROM city_functions WHERE code = 'special'), 151, 3000, 6, 12, true),
	('Психоневрологический диспансер', 'psychoneurological_dispensary', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Кризисный центр', 'crisis_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Реабилитационный центр', 'rehabilitation_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Центр занятости населения', 'employment_center', (SELECT id FROM city_functions WHERE code = 'social'), 151, 3000, 6, 12, true),
	('Микрозайм', 'microloan', (SELECT id FROM city_functions WHERE code = 'finance'), 151, 3000, 6, 12, true),
	('Благотворительный фонд', 'charitable_foundations', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Налоговая служба', 'tax_office', (SELECT id FROM city_functions WHERE code = 'special'), 151, 3000, 6, 12, true),
	('ЗАГС', 'registry_office', (SELECT id FROM city_functions WHERE code = 'social'), 151, 3000, 6, 12, true),
	('Детская поликлиника', 'child_doctor', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Детская больница', 'child_hospital', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Детский реабилитационный центр/санаторий', 'child_rehabilitation_center', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Детский хоспис', 'child_hospice', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Клуб для детей и подростков', 'child_teenager_club', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Спортивная секция', 'sport_section', (SELECT id FROM city_functions WHERE code = 'sport'), 151, 3000, 6, 12, false),
	('Частный детский сад', 'private_kids_garden', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Центр подготовки к ОГЭ/ЕГЭ', 'center_ege', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Железнодорожный вокзал', 'railway_terminal', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false),
	('Автобусный вокзал', 'bus_terminal', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false),
	('Железнодорожная станция', 'railway_station', (SELECT id FROM city_functions WHERE code = 'public_transport'), 151, 3000, 6, 12, false),
	('Дом творчества/культуры', 'culture_house', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Квест', 'quest', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Цирк', 'circus', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Центр развития ребенка', 'child_development_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Детский диспансер', 'children_dispensary', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Детская стоматология', 'child_dental', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Детская игровая комната', 'child_game_room', (SELECT id FROM city_functions WHERE code = 'kids_services'), 151, 3000, 6, 12, true),
	('Детские товары + для беременных', 'child_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true),
	('Картинная галерея', 'art_gallery', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Книжный магазин', 'book_store', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true),
	('Музыкальная школа', 'music_school', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, true),
	('Магазин товаров для творчества и рукоделия', 'art_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true),
	('Комната матери и ребенка', 'mother_child_room', (SELECT id FROM city_functions WHERE code = 'kids_services'), 151, 3000, 6, 12, true),
	('Прокат велосипедов', 'bike_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false),
	('Прокат автомобилей', 'car_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false),
	('Прокат самокатов', 'scooter_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false),
	('Товары для праздника', 'holiday_goods', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true),
	('Курсы иностранного языка (языковая школа)', 'language_school', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Магазин игрушек', 'toy_store', (SELECT id FROM city_functions WHERE code = 'goods'), 151, 3000, 6, 12, true),
	('Копировальный центр', 'copy_center', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Приют для животных', 'animal_shelter', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true),
	('Питомник', 'nursery', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true),
	('Птичий рынок', 'pet_market', (SELECT id FROM city_functions WHERE code = 'pet'), 151, 3000, 6, 12, true),
	('Агентство недвижимости', 'real_estate_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Свадебное агентство', 'wedding_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Прокат лимузинов', 'limousine_rental', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, false),
	('Туристическое агентство', 'tourist_agency', (SELECT id FROM city_functions WHERE code = 'service'), 151, 3000, 6, 12, true),
	('Автосалон', 'car_showroom', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true),
	('Автошкола', 'driving_schools', (SELECT id FROM city_functions WHERE code = 'car'), 151, 3000, 6, 12, true),
	('Санаторий', 'sanatorium', (SELECT id FROM city_functions WHERE code = 'health'), 151, 3000, 6, 12, true),
	('Центр дополнительного образования', 'continuing_education_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Центр повышения квалификации', 'advanced_training_center', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Частная школа', 'private_school', (SELECT id FROM city_functions WHERE code = 'education'), 151, 3000, 6, 12, true),
	('Военный комиссариат', 'military_commissariat', (SELECT id FROM city_functions WHERE code = 'army'), 151, 3000, 6, 12, true),
	('Общежитие для студентов', 'dormetory', (SELECT id FROM city_functions WHERE code = 'residential'), 151, 3000, 6, 12, true),
	('Пляж', 'beach', (SELECT id FROM city_functions WHERE code = 'nature'), 151, 3000, 6, 12, false),
	('Парк развлечений', 'amusement_park', (SELECT id FROM city_functions WHERE code = 'culture'), 151, 3000, 6, 12, false);

INSERT INTO municipality_types (full_name, short_name) VALUES
	('поселок', 'п.'),
	('муниципальный округ', 'м.о.'),
	('город', 'г.'),
	('городской округ', 'г.о.');

INSERT INTO administrative_unit_types (full_name, short_name) VALUES
	('район', 'р-н'),
	('внутригородской округ', 'вн.о.'),
	('сельский округ', 'с.о.');

END TRANSACTION;
