INSERT INTO basement_types (name, code) VALUES
    ('Бетонные столбы',	'code_1'),
    ('Комбинированный',	'code_2'),
    ('Ленточный',	'code_3'),
    ('Сборный',	'code_4'),
    ('Свайный',	'code_5'),
    ('Сплошной',	'code_6'),
    ('Столбчатый',	'code_7'),
    ('Иной',	'code_8'),
    ('Отсутствует',	'code_9');

INSERT INTO confessions (name, code) VALUES
    ('Адвентистская церковь',	'adventist'),
    ('Армянская апостольская церковь',	'armenian_apostolic'),
    ('Баптистская церковь',	'baptist'),
    ('Католическая церковь',	'catholic'),
    ('Евангельская церковь',	'evangelical'),
    ('Лютеранская церковь',	'lutheran'),
    ('Мормонская церковь',	'mormon'),
    ('Староверческая церковь',	'old_believers'),
    ('Православная церковь',	'orthodox'),
    ('Вишнуизм',	'vaishnavism');

INSERT INTO floor_types (name, code) VALUES
    ('Деревянные',	'code_1'),
    ('Железобетонные',	'code_2'),
    ('Иные',	'code_3');

INSERT INTO living_situations (name, code) VALUES
    ('Типичный нерабочий день',	'weekend'),
    ('Типичный рабочий день',	'working_day'),
    ('Свидание',	'date'),
    ('Свадьба',	'wedding'),
    ('Роды',	'birth'),
    ('Самоизоляция',	'self_isolation'),
    ('Заболевание ОРВИ',	'flu'),
    ('Травма',	'injury'),
    ('ДТП',	'road_accident'),
    ('Жертва административного правонарушения',	'offense'),
    ('Жертва уголовного правонарушения',	'crime'),
    ('Пьянство, наркомания',	'addiction'),
    ('Похороны',	'burial'),
    ('Заболевание туберкулезом',	'tuberculosis'),
    ('Заболевание венерическими заболеваниями',	'venereal'),
    ('Заболевание гепатитами',	'hepatitis'),
    ('Заболевание ВИЧ',	'hiv'),
    ('Заболевание новой короновирусной инфекцией',	'covid'),
    ('Заболевание сахарным диабетом',	'diabetes'),
    ('Заболевание раком',	'canser'),
    ('Новый год (01.01)',	'new_year'),
    ('Рождество (07.01)',	'сhristmas'),
    ('День святого Валентина (14.02)',	'valentine'),
    ('День защитника отечества(23.02)',	'defender_of_the_fatherland'),
    ('Международный женский день (08.03)',	'women_day'),
    ('Пасха, православная (19.04)',	'easter'),
    ('День труда (01.05)',	'labor'),
    ('День победы (09.05)',	'victory'),
    ('День России (12.06)',	'russia'),
    ('Алые паруса (18-27.06)',	'graduation'),
    ('Праздник жертвопрношения Курбан Байрам (31.07)',	'kurban_bayram'),
    ('День знаний (01.09)',	'knowledge'),
    ('День народного единства (04.11)',	'independence'),
    ('Увольнение',	'dismissal'),
    ('Переезд',	'moving');

INSERT INTO pollution_categories (name, code) VALUES
    ('Низкое',	'Low'),
    ('Среднее',	'Medium'),
    ('Высокое',	'High'),
    ('Очень высокое',	'Very High'),
    ('Нулевое',	'Zero');

INSERT INTO religions (name, code) VALUES
    ('Буддизм',	'buddhist'),
    ('Христианство',	'christian'),
    ('Индуизм',	'hindu'),
    ('Иудаизм',	'jewish'),
    ('Ислам',	'muslim');

INSERT INTO infrastructure_types (name, code) VALUES
    ('Базовая инфраструктура',	'basic'),
    ('Социальная инфраструктура',	'social'),
    ('Транспортная инфраструктура',	'transport'),
    ('Инфраструктура обслуживания населения', 'public'),
    ('Инфраструктура досуга',	'leisure'),
    ('Туристическая инфраструктура',	'tourism'),
    ('Места приложения труда', 'job');

INSERT INTO social_groups (name, code, parent_id) VALUES
    ('До трудоспособного возраста'                         , '1'   , null),
    ('Трудоспособные горожане'                             , '2'   , null),
    ('Горожане старше трудоспособного возраста'            , '3'   , null),
    ('Горожане с детьми'                                   , '4'   , null),
    ('Инвалиды'                                            , '5'   , null),
    ('Туристы'                                             , '6'   , null),
    ('Специальные группы'                                  , '7'   , null),
    ('Младенцы (0)'                                        , '1.1' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети до-детсадовского возраста (1-2)'                , '1.2' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети до-дошкольного возраста (3-6)'                  , '1.3' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети младшего школьного возраста (7-11)'             , '1.4' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Подростки младшего возраста (12-15)'                 , '1.5' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Подростки старшего возраста (16-18)'                 , '2.1' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Молодые работающие горожане (до 30 лет)'             , '2.2' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане среднего возраста (30-40)'       , '2.3' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане старшего возраста (40-60)'       , '2.4' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане пенсионного возраста (60+)'      , '2.5' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Люди старшего возраста (60-75 лет)'                  , '3.1' , (SELECT id FROM social_groups WHERE name = 'Горожане старше трудоспособного возраста')),
    ('Люди преклонного возраста (старше 75 лет)'           , '3.2' , (SELECT id FROM social_groups WHERE name = 'Горожане старше трудоспособного возраста')),
    ('Беременные женщины'                                  , '4.1' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с младенцами'                               , '4.2' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми до-детсадовского возраста (1-3)'   , '4.3' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми дошкольного возраста (3-7)'        , '4.4' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми младшего школьного возраста (7-11)', '4.5' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с подростками (12-18)'                      , '4.6' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Лица с инвалидностью по зрению'                      , '5.1' , (SELECT id FROM social_groups WHERE name = 'Инвалиды')),
    ('Лица с ограниченными возможностями передвижения'     , '5.2' , (SELECT id FROM social_groups WHERE name = 'Инвалиды')),
    ('Туристы в составе организованных групп'              , '6.1' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Неорганизованные туристы'                            , '6.2' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Приезжие к мероприятиям'                             , '6.3' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Приезжие по рабочим вопросам'                        , '6.4' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Студенты и учащиеся'                                 , '7.1' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Владельцы собак'                                     , '7.2' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Автовладельцы'                                       , '7.3' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Мотоциклисты'                                        , '7.4' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Велосипедисты'                                       , '7.5' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Трудовые мигранты'                                   , '7.6' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, православные'                              , '7.7' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, мусульмане'                                , '7.8' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, иудеи'                                     , '7.9' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, ведущие раздельный сбор мусора'            , '7.10', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, занимающиеся спортом'                      , '7.11', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, ведущие активный образ жизни'              , '7.12', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Самозанятые горожане'                                , '7.13', (SELECT id FROM social_groups WHERE name = 'Специальные группы'));

INSERT INTO city_functions (name, code, infrastructure_type_id) VALUES
    ('Жилье'                            , 'residential'     , (SELECT id FROM infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Мусор'                            , 'trash'           , (SELECT id FROM infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Образование'                      , 'education'       , (SELECT id FROM infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Здравоохранение'                  , 'health'          , (SELECT id FROM infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Религия'                          , 'religion'        , (SELECT id FROM infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Социальное обслуживание'          , 'social'          , (SELECT id FROM infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Личный транспорт'                 , 'car'             , (SELECT id FROM infrastructure_types WHERE name = 'Транспортная инфраструктура')),
    ('Уход за собой'                    , 'care'            , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Продовольствие'                   , 'rations'         , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Финансы'                          , 'finance'         , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Товары'                           , 'goods'           , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Питомцы'                          , 'pet'             , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Культура, развлечения, творчество', 'culture'         , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Спорт'                            , 'sport'           , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Питание'                          , 'food'            , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Товары для туристов'              , 'tourist'         , (SELECT id FROM infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Жилье для приезжих'               , 'hotel'           , (SELECT id FROM infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Достопримечательности'            , 'sights'          , (SELECT id FROM infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Специализированные учреждения'    , 'special'         , (SELECT id FROM infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Дипломатическое представительство', 'diplomacy'       , (SELECT id FROM infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Пешеходное пространство'          , 'pedestrian'      , (SELECT id FROM infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Общественный транспорт'           , 'public_transport', (SELECT id FROM infrastructure_types WHERE name = 'Транспортная инфраструктура')),
    ('Доставка'                         , 'delivery'        , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Услуги'                           , 'service'         , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Природа'                          , 'nature'          , (SELECT id FROM infrastructure_types WHERE name = 'Инфраструктура досуга'));

INSERT INTO service_types (name, code, capacity_min, capacity_max, city_function_id, status_min, status_max) VALUES
    ('Детский сад'                                      , 'kindergartens'            ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Образование')                      ,          9,         18),
    ('Школа'                                            , 'schools'                  ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Образование')                      ,         12,         24),
    ('Учреждение среднего профессионального образования', 'colleges'                 ,            3,            6, (SELECT id FROM city_functions WHERE name = 'Образование')                      ,         18,         36),
    ('Учреждение высшего профессионального образования' , 'universities'             ,            5,           10, (SELECT id FROM city_functions WHERE name = 'Образование')                      ,         18,         36),
    ('Поликлиника'                                      , 'policlinics'              ,            5,            7, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         12,         24),
    ('Больница'                                         , 'hospitals'                ,            3,            8, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         12,         24),
    ('Женская консультация'                             , 'woman_doctors'            ,            2,            4, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         12,         24),
    ('Роддом'                                           , 'maternity_hospitals'      ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         18,         36),
    ('Стоматология'                                     , 'dentists'                 ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,          6,         12),
    ('Аптека'                                           , 'pharmacies'               ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,          4,          8),
    ('Диспансер'                                        , 'health_centers'           ,            2,            6, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         18,         36),
    ('Кладбище/крематорий'                              , 'cemeteries'               ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Религия')                          ,         24,         36),
    ('Религиозный объект'                               , 'churches'                 ,            1,            6, (SELECT id FROM city_functions WHERE name = 'Религия')                          ,         12,         24),
    ('Автозаправка'                                     , 'gas_stations'             ,            3,            5, (SELECT id FROM city_functions WHERE name = 'Личный транспорт')                 ,          6,         12),
    ('Электрозаправка'                                  , 'charging_stations'        ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Личный транспорт')                 ,          6,         12),
    ('Рынок'                                            , 'markets'                  ,            3,            6, (SELECT id FROM city_functions WHERE name = 'Продовольствие')                   ,          9,         18),
    ('Магазин у дома'                                   , 'conveniences'             ,            3,            5, (SELECT id FROM city_functions WHERE name = 'Продовольствие')                   ,          3,          6),
    ('Универсам/супермаркет/гипермаркет'                , 'supermarkets'             ,            5,            8, (SELECT id FROM city_functions WHERE name = 'Продовольствие')                   ,          9,         18),
    ('Арт пространство'                                 , 'art_spaces'               ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),          6,         12),
    ('Зоопарк'                                          , 'zoos'                     ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Библиотека'                                       , 'libraries'                ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Театр/Концертный зал'                             , 'theaters'                 ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Музей'                                            , 'museums'                  ,            2,            9, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Кинотеатр'                                        , 'cinemas'                  ,            1,            6, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Бар/Паб/Кальянная'                                , 'bars'                     ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Питание')                          ,          3,          6),
    ('Булочная'                                         , 'bakeries'                 ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Питание')                          ,          3,          6),
    ('Кафе/столовая'                                    , 'cafes'                    ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Питание')                          ,          3,          6),
    ('Ресторан'                                         , 'restaurants'              ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Питание')                          ,          3,          6),
    ('Фастфуд'                                          , 'fastfoods'                ,            1,            7, (SELECT id FROM city_functions WHERE name = 'Питание')                          ,          3,          6),
    ('Урна'                                             , 'garbage_containers'       ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Мусор')                            ,          6,         12),
    ('Свалка'                                           , 'garbage_dumps'            ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Мусор')                            ,         12,         24),
    ('Точка раздельного сбора'                          , 'recycling_stations'       ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Мусор')                            ,          3,          6),
    ('Баня'                                             , 'saunas'                   ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Уход за собой')                    ,          4,          8),
    ('Спортивная площадка'                              , 'sportgrounds'             ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,          6,         12),
    ('Бассейн'                                          , 'swimming_pools'           ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,          9,         18),
    ('Ветеринарная клиника'                             , 'veterinaries'             ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Питомцы')                          ,          6,         12),
    ('Жилье'                                            , 'houses'                   ,            1,            9, (SELECT id FROM city_functions WHERE name = 'Жилье')                            ,          8,         16),
    ('Отделение банка'                                  , 'banks'                    ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Финансы')                          ,          6,         12),
    ('Банкомат'                                         , 'atms'                     ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Финансы')                          ,          6,         12),
    ('Полиция'                                          , 'police_stations'          ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         12,         24),
    ('Пожарная станция'                                 , 'fire_stations'            ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         12,         24),
    ('Оптика'                                           , 'optics'                   ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,          4,          8),
    ('Торгово-развлекательный центр'                    , 'shopping_centers'         ,            6,           10, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),         12,         24),
    ('Визовый центр'                                    , 'visa_centers'             ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Дипломатическое представительство'),          6,         12),
    ('Консульство/посольство'                           , 'consulates'               ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Дипломатическое представительство'),         12,         24),
    ('Клиника'                                          , 'clinics'                  ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,          6,         12),
    ('Аквапарк'                                         , 'aquaparks'                ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,         12,         24),
    ('Фитнес клуб'                                      , 'fitness_clubs'            ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,          6,         12),
    ('Спортивный центр'                                 , 'sport_centers'            ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,         12,         24),
    ('Спортивный клуб'                                  , 'sport_clubs'              ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,          9,         18),
    ('Стадион'                                          , 'stadiums'                 ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Спорт')                            ,         18,         36),
    ('Гостиница'                                        , 'hotels'                   ,            2,            6, (SELECT id FROM city_functions WHERE name = 'Жилье для приезжих')               ,          6,         12),
    ('Гостевой дом'                                     , 'guest_houses'             ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Жилье для приезжих')               ,          6,         12),
    ('Хостел'                                           , 'hostels'                  ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Жилье для приезжих')               ,          6,         12),
    ('Общежитие'                                        , 'dormitories'              ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Жилье для приезжих')               ,          6,         12),
    ('Автосервис'                                       , 'repair_stations'          ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Личный транспорт')                 ,          6,         12),
    ('Автопарковка'                                     , 'parkings'                 ,            1,            6, (SELECT id FROM city_functions WHERE name = 'Личный транспорт')                 ,          6,         12),
    ('Салон красоты/парикмахерская'                     , 'beauty_salons'            ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Уход за собой')                    ,          3,          6),
    ('Массажный салон (spa)'                            , 'spas'                     ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Уход за собой')                    ,          3,          6),
    ('Почта'                                            , 'post_offices'             ,            3,            5, (SELECT id FROM city_functions WHERE name = 'Доставка')                         ,         12,         24),
    ('Пункт выдачи'                                     , 'outposts'                 ,            3,            6, (SELECT id FROM city_functions WHERE name = 'Доставка')                         ,          6,         12),
    ('Почтовый ящик'                                    , 'post_boxes'               ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Доставка')                         ,         12,         24),
    ('Жилищное (жкх, жилкомсервис)'                     , 'housing_services'         ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Жилье')                            ,         12,         24),
    ('Детская площадка'                                 , 'playgrounds'              ,            1,            9, (SELECT id FROM city_functions WHERE name = 'Жилье')                            ,          6,         12),
    ('Станция скорой помощи'                            , 'ambulance_stations'       ,            2,            6, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         12,         24),
    ('МФЦ'                                              , 'multifunctional_centers'  ,            2,            6, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('Суд'                                              , 'courts'                   ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('ИОГВ'                                             , 'executive_institutions'   ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('ПФР'                                              , 'pension_funds'            ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('Тюрьма'                                           , 'prisons'                  ,            3,            7, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         24,         48),
    ('Соц(Дом престарелых/Детский дом)'                 , 'orphanages'               ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Государственное учреждение'                       , 'state_institutions'       ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Станция метро'                                    , 'metro_stations'           ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Общественный транспорт')           ,         12,         24),
    ('Ремонт обуви и одежды'                            , 'clothing_repairings'      ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          4,          8),
    ('Фотоателье'                                       , 'photo_studios'            ,            1,            3, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          4,          8),
    ('Ремонт часов'                                     , 'watch_repairings'         ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          4,          8),
    ('Букмекерская контора'                             , 'bookmaker_offices'        ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          4,          8),
    ('Похоронные услуги'                                , 'rituals'                  ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          9,         18),
    ('Хозяйственный'                                    , 'hardware_stores'          ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          8,         16),
    ('Инструменты'                                      , 'instrument_stores'        ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          8,         16),
    ('Бытовая техника, электроника'                     , 'electronic_stores'        ,            2,            4, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          6,         12),
    ('Магазин одежды/обуви/аксессуаров'                 , 'clothing_stores'          ,            2,           10, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          8,         16),
    ('Табак'                                            , 'tobacco_stores'           ,            2,           10, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          8,         16),
    ('Спорттовары'                                      , 'sporting_stores'          ,            2,           10, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          6,         12),
    ('Ювелирная мастерская'                             , 'jewelry_stores'           ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          6,         12),
    ('Цветы'                                            , 'flower_stores'            ,            2,            3, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          6,         12),
    ('Ломбард'                                          , 'pawnshops'                ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Товары')                           ,          6,         12),
    ('Зоомагазин'                                       , 'pet_shops'                ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Питомцы')                          ,          4,          8),
    ('Площадка для выгула собак'                        , 'dog_playgrounds'          ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Питомцы')                          ,          6,         12),
    ('Рекреационная зона'                               , 'recreational_areas'       ,            1,            7, (SELECT id FROM city_functions WHERE name = 'Природа')                          ,         12,         24),
    ('Набережная'                                       , 'embankments'              ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Природа')                          ,         24,         36),
    ('Магазин сувениров'                                , 'souvenir_shops'           ,            1,            6, (SELECT id FROM city_functions WHERE name = 'Товары для туристов')              ,          9,         18),
    ('Памятник'                                         , 'monuments'                ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Достопримечательности')            ,         12,         24),
    ('Архитектурное сооружение или ансамбль'            , 'architectural_ensembles'  ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Достопримечательности')            ,         24,         36),
    ('Объект культурного наследия'                      , 'culturalheritage_sites'   ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Достопримечательности')            ,         24,         36),
    ('Боулинг, бильярд'                                 , 'bowlings'                 ,            1,            5, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),          6,         12),
    ('Органы опеки'                                     , 'child_protections'        ,            2,            4, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Мусоро-перерабатывающий завод'                    , 'wasterecycling_plants'    ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Мусор')                            ,         12,         24),
    ('Улица'                                            , 'streets'                  ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Пешеходное пространство')          ,         12,         24),
    ('Пешеходный переход'                               , 'crosswalks'               ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Пешеходное пространство')          ,         12,         24),
    ('Пешеходная дорожка'                               , 'footpaths'                ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Пешеходное пространство')          ,         12,         24),
    ('Хоспис'                                           , 'hospices'                 ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Здравоохранение')                  ,         18,         36),
    ('Центр социальной помощи'                          , 'social_assistance_centers',            2,            3, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('Паспортный стол'                                  , 'passport_offices'         ,            2,            5, (SELECT id FROM city_functions WHERE name = 'Социальное обслуживание')          ,         12,         24),
    ('Миграционная служба'                              , 'migration_services'       ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Прокуратура'                                      , 'prosecutor_offices'       ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Судебные приставы'                                , 'bailiffs'                 ,            1,            4, (SELECT id FROM city_functions WHERE name = 'Специализированные учреждения')    ,         18,         36),
    ('Остановка общественного транспорта'               , 'stops'                    ,            5,           10, (SELECT id FROM city_functions WHERE name = 'Общественный транспорт')           ,         12,         24),
    ('Изготовление ключей'                              , 'key_services'             ,            1,            2, (SELECT id FROM city_functions WHERE name = 'Услуги')                           ,          4,          8),
    ('Клуб'                                             , 'clubs'                    ,            1,            6, (SELECT id FROM city_functions WHERE name = 'Культура, развлечения, творчество'),          6,         12),
    ('Видовая точка'                                    , 'viewspots'                ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Достопримечательности')            ,         12,         24),
    ('Памятное место'                                   , 'memorable_places'         ,            1,           10, (SELECT id FROM city_functions WHERE name = 'Достопримечательности')            ,         24,         36);