INSERT INTO living_situations (name, code) VALUES
    ('Типичный нерабочий день',	'weekend'),
    ('Типичный рабочий день',	'working_day'),
    ('Свидание',	'date'),
    ('Свадьба',	'wedding'),
    ('Роды',	'birth'),
    ('Самоизоляция',	'self_isolation'),
    ('Заболевание ОРВИ',	'flu'),
    ('Травма',	'injury'),
    ('ДТП',	'road_accident'),
    ('Жертва административного правонарушения',	'offense'),
    ('Жертва уголовного правонарушения',	'crime'),
    ('Пьянство, наркомания',	'addiction'),
    ('Похороны',	'burial'),
    ('Заболевание туберкулезом',	'tuberculosis'),
    ('Заболевание венерическими заболеваниями',	'venereal'),
    ('Заболевание гепатитами',	'hepatitis'),
    ('Заболевание ВИЧ',	'hiv'),
    ('Заболевание новой короновирусной инфекцией',	'covid'),
    ('Заболевание сахарным диабетом',	'diabetes'),
    ('Заболевание раком',	'canser'),
    ('Новый год (01.01)',	'new_year'),
    ('Рождество (07.01)',	'сhristmas'),
    ('День святого Валентина (14.02)',	'valentine'),
    ('День защитника отечества(23.02)',	'defender_of_the_fatherland'),
    ('Международный женский день (08.03)',	'women_day'),
    ('Пасха, православная (19.04)',	'easter'),
    ('День труда (01.05)',	'labor'),
    ('День победы (09.05)',	'victory'),
    ('День России (12.06)',	'russia'),
    ('Алые паруса (18-27.06)',	'graduation'),
    ('Праздник жертвопрношения Курбан Байрам (31.07)',	'kurban_bayram'),
    ('День знаний (01.09)',	'knowledge'),
    ('День народного единства (04.11)',	'independence'),
    ('Увольнение',	'dismissal'),
    ('Переезд',	'moving');

INSERT INTO city_infrastructure_types (name, code) VALUES
    ('Базовая инфраструктура',	'basic'),
    ('Социальная инфраструктура',	'social'),
    ('Транспортная инфраструктура',	'transport'),
    ('Инфраструктура обслуживания населения', 'public'),
    ('Инфраструктура досуга',	'leisure'),
    ('Туристическая инфраструктура',	'tourism'),
    ('Места приложения труда', 'job');

INSERT INTO social_groups (name, code, parent_id) VALUES
    ('До трудоспособного возраста'                         , '1'   , null),
    ('Трудоспособные горожане'                             , '2'   , null),
    ('Горожане старше трудоспособного возраста'            , '3'   , null),
    ('Горожане с детьми'                                   , '4'   , null),
    ('Инвалиды'                                            , '5'   , null),
    ('Туристы'                                             , '6'   , null),
    ('Специальные группы'                                  , '7'   , null),
    ('Младенцы (0)'                                        , '1.1' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети до-детсадовского возраста (1-2)'                , '1.2' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети до-дошкольного возраста (3-6)'                  , '1.3' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Дети младшего школьного возраста (7-11)'             , '1.4' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Подростки младшего возраста (12-15)'                 , '1.5' , (SELECT id FROM social_groups WHERE name = 'До трудоспособного возраста')),
    ('Подростки старшего возраста (16-18)'                 , '2.1' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Молодые работающие горожане (до 30 лет)'             , '2.2' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане среднего возраста (30-40)'       , '2.3' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане старшего возраста (40-60)'       , '2.4' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Работающие горожане пенсионного возраста (60+)'      , '2.5' , (SELECT id FROM social_groups WHERE name = 'Трудоспособные горожане')),
    ('Люди старшего возраста (60-75 лет)'                  , '3.1' , (SELECT id FROM social_groups WHERE name = 'Горожане старше трудоспособного возраста')),
    ('Люди преклонного возраста (старше 75 лет)'           , '3.2' , (SELECT id FROM social_groups WHERE name = 'Горожане старше трудоспособного возраста')),
    ('Беременные женщины'                                  , '4.1' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с младенцами'                               , '4.2' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми до-детсадовского возраста (1-3)'   , '4.3' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми дошкольного возраста (3-7)'        , '4.4' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с детьми младшего школьного возраста (7-11)', '4.5' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Горожане с подростками (12-18)'                      , '4.6' , (SELECT id FROM social_groups WHERE name = 'Горожане с детьми')),
    ('Лица с инвалидностью по зрению'                      , '5.1' , (SELECT id FROM social_groups WHERE name = 'Инвалиды')),
    ('Лица с ограниченными возможностями передвижения'     , '5.2' , (SELECT id FROM social_groups WHERE name = 'Инвалиды')),
    ('Туристы в составе организованных групп'              , '6.1' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Неорганизованные туристы'                            , '6.2' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Приезжие к мероприятиям'                             , '6.3' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Приезжие по рабочим вопросам'                        , '6.4' , (SELECT id FROM social_groups WHERE name = 'Туристы')),
    ('Студенты и учащиеся'                                 , '7.1' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Владельцы собак'                                     , '7.2' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Автовладельцы'                                       , '7.3' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Мотоциклисты'                                        , '7.4' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Велосипедисты'                                       , '7.5' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Трудовые мигранты'                                   , '7.6' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, православные'                              , '7.7' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, мусульмане'                                , '7.8' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Верующие, иудеи'                                     , '7.9' , (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, ведущие раздельный сбор мусора'            , '7.10', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, занимающиеся спортом'                      , '7.11', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Горожане, ведущие активный образ жизни'              , '7.12', (SELECT id FROM social_groups WHERE name = 'Специальные группы')),
    ('Самозанятые горожане'                                , '7.13', (SELECT id FROM social_groups WHERE name = 'Специальные группы'));

INSERT INTO city_functions (name, code, city_infrastructure_type_id) VALUES
    ('Жилье'                            , 'residential'     , (SELECT id FROM city_infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Мусор'                            , 'trash'           , (SELECT id FROM city_infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Образование'                      , 'education'       , (SELECT id FROM city_infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Здравоохранение'                  , 'health'          , (SELECT id FROM city_infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Религия'                          , 'religion'        , (SELECT id FROM city_infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Социальное обслуживание'          , 'social'          , (SELECT id FROM city_infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Личный транспорт'                 , 'car'             , (SELECT id FROM city_infrastructure_types WHERE name = 'Транспортная инфраструктура')),
    ('Уход за собой'                    , 'care'            , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Продовольствие'                   , 'rations'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Финансы'                          , 'finance'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Товары'                           , 'goods'           , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Питомцы'                          , 'pet'             , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Культура, развлечения, творчество', 'culture'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Спорт'                            , 'sport'           , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Питание'                          , 'food'            , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура досуга')),
    ('Товары для туристов'              , 'tourist'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Жилье для приезжих'               , 'hotel'           , (SELECT id FROM city_infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Достопримечательности'            , 'sights'          , (SELECT id FROM city_infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Специализированные учреждения'    , 'special'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Социальная инфраструктура')),
    ('Дипломатическое представительство', 'diplomacy'       , (SELECT id FROM city_infrastructure_types WHERE name = 'Туристическая инфраструктура')),
    ('Пешеходное пространство'          , 'pedestrian'      , (SELECT id FROM city_infrastructure_types WHERE name = 'Базовая инфраструктура')),
    ('Общественный транспорт'           , 'public_transport', (SELECT id FROM city_infrastructure_types WHERE name = 'Транспортная инфраструктура')),
    ('Доставка'                         , 'delivery'        , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Услуги'                           , 'service'         , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура обслуживания населения')),
    ('Природа'                          , 'nature'          , (SELECT id FROM city_infrastructure_types WHERE name = 'Инфраструктура досуга'));

INSERT INTO city_service_types (name, code, capacity_min, capacity_max, city_function_id, status_min, status_max, is_building) VALUES
    ('Детский сад'                                       , 'kindergartens'             , 1,            3, (SELECT id FROM city_functions WHERE code = 'education'),          9, 18, true),
    ('Школа'                                             , 'schools'                   , 2,            5, (SELECT id FROM city_functions WHERE code = 'education'),         12, 24, true),
    ('Учреждение среднего профессионального образования' , 'colleges'                  , 3,            6, (SELECT id FROM city_functions WHERE code = 'education'),         18, 36, true),
    ('Учреждение высшего профессионального образования'  , 'universities'              , 5,           10, (SELECT id FROM city_functions WHERE code = 'education'),         18, 36, true),
    ('Поликлиника'                                       , 'policlinics'               , 5,            7, (SELECT id FROM city_functions WHERE code = 'health'),            12, 24, true),
    ('Больница'                                          , 'hospitals'                 , 3,            8, (SELECT id FROM city_functions WHERE code = 'health'),            12, 24, true),
    ('Женская консультация'                              , 'woman_doctors'             , 2,            4, (SELECT id FROM city_functions WHERE code = 'health'),            12, 24, true),
    ('Роддом'                                            , 'maternity_hospitals'       , 1,            3, (SELECT id FROM city_functions WHERE code = 'health'),            18, 36, true),
    ('Стоматология'                                      , 'dentists'                  , 1,            2, (SELECT id FROM city_functions WHERE code = 'health'),             6, 12, true),
    ('Аптека'                                            , 'pharmacies'                , 1,            5, (SELECT id FROM city_functions WHERE code = 'health'),             4,  8, true),
    ('Диспансер'                                         , 'health_centers'            , 2,            6, (SELECT id FROM city_functions WHERE code = 'health'),            18, 36, true),
    ('Кладбище/крематорий'                               , 'cemeteries'                , 1,            3, (SELECT id FROM city_functions WHERE code = 'religion'),          24, 36, false),
    ('Религиозный объект'                                , 'churches'                  , 1,            6, (SELECT id FROM city_functions WHERE code = 'religion'),          12, 24, true),
    ('Автозаправка'                                      , 'gas_stations'              , 3,            5, (SELECT id FROM city_functions WHERE code = 'car'),                6, 12, false),
    ('Электрозаправка'                                   , 'charging_stations'         , 1,            3, (SELECT id FROM city_functions WHERE code = 'car'),                6, 12, false),
    ('Рынок'                                             , 'markets'                   , 3,            6, (SELECT id FROM city_functions WHERE code = 'rations'),            9, 18, true),
    ('Магазин у дома'                                    , 'conveniences'              , 3,            5, (SELECT id FROM city_functions WHERE code = 'rations'),            3,  6, true),
    ('Универсам/супермаркет/гипермаркет'                 , 'supermarkets'              , 5,            8, (SELECT id FROM city_functions WHERE code = 'rations'),            9, 18, true),
    ('Арт пространство'                                  , 'art_spaces'                , 1,            4, (SELECT id FROM city_functions WHERE code = 'culture'),            6, 12, true),
    ('Зоопарк'                                           , 'zoos'                      , 2,            5, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Библиотека'                                        , 'libraries'                 , 1,            3, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Театр/Концертный зал'                              , 'theaters'                  , 2,            5, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Музей'                                             , 'museums'                   , 2,            9, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Кинотеатр'                                         , 'cinemas'                   , 1,            6, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Бар/Паб/Кальянная'                                 , 'bars'                      , 1,            4, (SELECT id FROM city_functions WHERE code = 'food'),               3,  6, true),
    ('Булочная'                                          , 'bakeries'                  , 1,            4, (SELECT id FROM city_functions WHERE code = 'food'),               3,  6, true),
    ('Кафе/столовая'                                     , 'cafes'                     , 1,            5, (SELECT id FROM city_functions WHERE code = 'food'),               3,  6, true),
    ('Ресторан'                                          , 'restaurants'               , 1,            4, (SELECT id FROM city_functions WHERE code = 'food'),               3,  6, true),
    ('Фастфуд'                                           , 'fastfoods'                 , 1,            7, (SELECT id FROM city_functions WHERE code = 'food'),               3,  6, true),
    ('Урна'                                              , 'garbage_containers'        , 1,           10, (SELECT id FROM city_functions WHERE code = 'trash'),              6, 12, false),
    ('Свалка'                                            , 'garbage_dumps'             , 1,            2, (SELECT id FROM city_functions WHERE code = 'trash'),             12, 24, false),
    ('Точка раздельного сбора'                           , 'recycling_stations'        , 1,            4, (SELECT id FROM city_functions WHERE code = 'trash'),              3,  6, false),
    ('Баня'                                              , 'saunas'                    , 1,            3, (SELECT id FROM city_functions WHERE code = 'care'),               4,  8, true),
    ('Спортивная площадка'                               , 'sportgrounds'              , 1,            3, (SELECT id FROM city_functions WHERE code = 'sport'),              6, 12, false),
    ('Бассейн'                                           , 'swimming_pools'            , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),              9, 18, true),
    ('Ветеринарная клиника'                              , 'veterinaries'              , 1,            3, (SELECT id FROM city_functions WHERE code = 'pet'),                6, 12, true),
    ('Жилье'                                             , 'houses'                    , 1,            9, (SELECT id FROM city_functions WHERE code = 'residential'),        8, 16, true),
    ('Отделение банка'                                   , 'banks'                     , 2,            3, (SELECT id FROM city_functions WHERE code = 'finance'),            6, 12, true),
    ('Банкомат'                                          , 'atms'                      , 1,            3, (SELECT id FROM city_functions WHERE code = 'finance'),            6, 12, true),
    ('Полиция'                                           , 'police_stations'           , 1,            3, (SELECT id FROM city_functions WHERE code = 'special'),           12, 24, true),
    ('Пожарная станция'                                  , 'fire_stations'             , 1,            3, (SELECT id FROM city_functions WHERE code = 'special'),           12, 24, true),
    ('Оптика'                                            , 'optics'                    , 1,            5, (SELECT id FROM city_functions WHERE code = 'health'),             4,  8, true),
    ('Торгово-развлекательный центр'                     , 'shopping_centers'          , 6,           10, (SELECT id FROM city_functions WHERE code = 'culture'),           12, 24, true),
    ('Визовый центр'                                     , 'visa_centers'              , 1,            4, (SELECT id FROM city_functions WHERE code = 'diplomacy'),          6, 12, true),
    ('Консульство/посольство'                            , 'consulates'                , 1,            5, (SELECT id FROM city_functions WHERE code = 'diplomacy'),         12, 24, true),
    ('Клиника'                                           , 'clinics'                   , 2,            5, (SELECT id FROM city_functions WHERE code = 'health'),             6, 12, true),
    ('Аквапарк'                                          , 'aquaparks'                 , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),             12, 24, true),
    ('Фитнес клуб'                                       , 'fitness_clubs'             , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),              6, 12, true),
    ('Спортивный центр'                                  , 'sport_centers'             , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),             12, 24, true),
    ('Спортивный клуб'                                   , 'sport_clubs'               , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),              9, 18, true),
    ('Стадион'                                           , 'stadiums'                  , 1,            4, (SELECT id FROM city_functions WHERE code = 'sport'),             18, 36, true),
    ('Гостиница'                                         , 'hotels'                    , 2,            6, (SELECT id FROM city_functions WHERE code = 'hotel'),              6, 12, true),
    ('Гостевой дом'                                      , 'guest_houses'              , 1,            3, (SELECT id FROM city_functions WHERE code = 'hotel'),              6, 12, true),
    ('Хостел'                                            , 'hostels'                   , 1,            2, (SELECT id FROM city_functions WHERE code = 'hotel'),              6, 12, true),
    ('Общежитие'                                         , 'dormitories'               , 1,            2, (SELECT id FROM city_functions WHERE code = 'hotel'),              6, 12, true),
    ('Автосервис'                                        , 'repair_stations'           , 1,            2, (SELECT id FROM city_functions WHERE code = 'car'),                6, 12, true),
    ('Автопарковка'                                      , 'parkings'                  , 1,            6, (SELECT id FROM city_functions WHERE code = 'car'),                6, 12, false),
    ('Салон красоты/парикмахерская'                      , 'beauty_salons'             , 1,            2, (SELECT id FROM city_functions WHERE code = 'care'),               3,  6, true),
    ('Массажный салон (spa)'                             , 'spas'                      , 1,            2, (SELECT id FROM city_functions WHERE code = 'care'),               3,  6, true),
    ('Почта'                                             , 'post_offices'              , 3,            5, (SELECT id FROM city_functions WHERE code = 'delivery'),          12, 24, true),
    ('Пункт выдачи'                                      , 'outposts'                  , 3,            6, (SELECT id FROM city_functions WHERE code = 'delivery'),           6, 12, true),
    ('Почтовый ящик'                                     , 'post_boxes'                , 1,            5, (SELECT id FROM city_functions WHERE code = 'delivery'),          12, 24, true),
    ('Жилищное (жкх, жилкомсервис)'                      , 'housing_services'          , 1,            4, (SELECT id FROM city_functions WHERE code = 'residential'),       12, 24, true),
    ('Детская площадка'                                  , 'playgrounds'               , 1,            9, (SELECT id FROM city_functions WHERE code = 'residential'),        6, 12, false),
    ('Станция скорой помощи'                             , 'ambulance_stations'        , 2,            6, (SELECT id FROM city_functions WHERE code = 'health'),            12, 24, true),
    ('МФЦ'                                               , 'multifunctional_centers'   , 2,            6, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('Суд'                                               , 'courts'                    , 2,            3, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('ИОГВ'                                              , 'executive_institutions'    , 2,            3, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('ПФР'                                               , 'pension_funds'             , 2,            3, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('Тюрьма'                                            , 'prisons'                   , 3,            7, (SELECT id FROM city_functions WHERE code = 'special'),           24, 48, true),
    ('Соц(Дом престарелых/Детский дом)'                  , 'orphanages'                , 1,            5, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Государственное учреждение'                        , 'state_institutions'        , 1,            5, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Станция метро'                                     , 'metro_stations'            , 1,            2, (SELECT id FROM city_functions WHERE code = 'public_transport'),  12, 24, false),
    ('Ремонт обуви и одежды'                             , 'clothing_repairings'       , 1,            3, (SELECT id FROM city_functions WHERE code = 'service'),            4,  8, true),
    ('Фотоателье'                                        , 'photo_studios'             , 1,            3, (SELECT id FROM city_functions WHERE code = 'service'),            4,  8, true),
    ('Ремонт часов'                                      , 'watch_repairings'          , 1,            2, (SELECT id FROM city_functions WHERE code = 'service'),            4,  8, true),
    ('Букмекерская контора'                              , 'bookmaker_offices'         , 2,            5, (SELECT id FROM city_functions WHERE code = 'service'),            4,  8, true),
    ('Похоронные услуги'                                 , 'rituals'                   , 1,            2, (SELECT id FROM city_functions WHERE code = 'service'),            9, 18, true),
    ('Хозяйственный'                                     , 'hardware_stores'           , 1,            2, (SELECT id FROM city_functions WHERE code = 'goods'),              8, 16, true),
    ('Инструменты'                                       , 'instrument_stores'         , 1,            2, (SELECT id FROM city_functions WHERE code = 'goods'),              8, 16, true),
    ('Бытовая техника, электроника'                      , 'electronic_stores'         , 2,            4, (SELECT id FROM city_functions WHERE code = 'goods'),              6, 12, true),
    ('Магазин одежды/обуви/аксессуаров'                  , 'clothing_stores'           , 2,           10, (SELECT id FROM city_functions WHERE code = 'goods'),              8, 16, true),
    ('Табак'                                             , 'tobacco_stores'            , 2,           10, (SELECT id FROM city_functions WHERE code = 'goods'),              8, 16, true),
    ('Спорттовары'                                       , 'sporting_stores'           , 2,           10, (SELECT id FROM city_functions WHERE code = 'goods'),              6, 12, true),
    ('Ювелирная мастерская'                              , 'jewelry_stores'            , 2,            3, (SELECT id FROM city_functions WHERE code = 'goods'),              6, 12, true),
    ('Цветы'                                             , 'flower_stores'             , 2,            3, (SELECT id FROM city_functions WHERE code = 'goods'),              6, 12, true),
    ('Ломбард'                                           , 'pawnshops'                 , 1,            2, (SELECT id FROM city_functions WHERE code = 'goods'),              6, 12, true),
    ('Зоомагазин'                                        , 'pet_shops'                 , 1,            4, (SELECT id FROM city_functions WHERE code = 'pet'),                4,  8, true),
    ('Площадка для выгула собак'                         , 'dog_playgrounds'           , 2,            5, (SELECT id FROM city_functions WHERE code = 'pet'),                6, 12, false),
    ('Рекреационная зона'                                , 'recreational_areas'        , 1,            7, (SELECT id FROM city_functions WHERE code = 'nature'),            12, 24, false),
    ('Набережная'                                        , 'embankments'               , 2,            5, (SELECT id FROM city_functions WHERE code = 'nature'),            24, 36, false),
    ('Магазин сувениров'                                 , 'souvenir_shops'            , 1,            6, (SELECT id FROM city_functions WHERE code = 'tourist'),            9, 18, true),
    ('Памятник'                                          , 'monuments'                 , 1,           10, (SELECT id FROM city_functions WHERE code = 'sights'),            12, 24, false),
    ('Архитектурное сооружение или ансамбль'             , 'architectural_ensembles'   , 1,           10, (SELECT id FROM city_functions WHERE code = 'sights'),            24, 36, false),
    ('Объект культурного наследия'                       , 'culturalheritage_sites'    , 1,           10, (SELECT id FROM city_functions WHERE code = 'sights'),            24, 36, false),
    ('Боулинг, бильярд'                                  , 'bowlings'                  , 1,            5, (SELECT id FROM city_functions WHERE code = 'culture'),            6, 12, true),
    ('Органы опеки'                                      , 'child_protections'         , 2,            4, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Мусоро-перерабатывающий завод'                     , 'wasterecycling_plants'     , 1,            2, (SELECT id FROM city_functions WHERE code = 'trash'),             12, 24, true),
    ('Улица'                                             , 'streets'                   , 1,           10, (SELECT id FROM city_functions WHERE code = 'pedestrian'),        12, 24, false),
    ('Пешеходный переход'                                , 'crosswalks'                , 1,           10, (SELECT id FROM city_functions WHERE code = 'pedestrian'),        12, 24, false),
    ('Пешеходная дорожка'                                , 'footpaths'                 , 1,           10, (SELECT id FROM city_functions WHERE code = 'pedestrian'),        12, 24, false),
    ('Хоспис'                                            , 'hospices'                  , 1,            4, (SELECT id FROM city_functions WHERE code = 'health'),            18, 36, true),
    ('Центр социальной помощи'                           , 'social_assistance_centers' , 2,            3, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('Паспортный стол'                                   , 'passport_offices'          , 2,            5, (SELECT id FROM city_functions WHERE code = 'social'),            12, 24, true),
    ('Миграционная служба'                               , 'migration_services'        , 1,            4, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Прокуратура'                                       , 'prosecutor_offices'        , 1,            4, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Судебные приставы'                                 , 'bailiffs'                  , 1,            4, (SELECT id FROM city_functions WHERE code = 'special'),           18, 36, true),
    ('Остановка общественного транспорта'                , 'stops'                     , 5,           10, (SELECT id FROM city_functions WHERE code = 'public_transport'),  12, 24, false),
    ('Клуб'                                              , 'clubs'                     , 1,            6, (SELECT id FROM city_functions WHERE code = 'culture'),            6, 12, true),
    ('Видовая точка'                                     , 'viewspots'                 , 1,           10, (SELECT id FROM city_functions WHERE code = 'sights'),            12, 24, false),
    ('Памятное место'                                    , 'memorable_places'          , 1,           10, (SELECT id FROM city_functions WHERE code = 'sights'),            24, 36, false),
    ('Услуги'                                            , 'services'                  , 1,            3, (SELECT id FROM city_functions WHERE code = 'service'),            4,  8, true);

INSERT INTO municipality_types (full_name, short_name) VALUES
    ('город'               , 'г.'  ),
    ('муниципальный округ' , 'м.о.'),
    ('городской округ'     , 'г.о.'),
    ('поселок'             , 'п.'  );

INSERT INTO administrative_unit_types (full_name, short_name) VALUES
    ('район'                 , 'р-н'  ),
    ('внутригородской округ' , 'вн.о.'),
    ('сельский округ'        , 'с.о.' );